version: '3'

services:
  db:
    image: postgres:10.3-alpine
    volumes:
      - /data/cwopp:/var/lib/postgresql/data
  web:
    image: cait/cwopp_django
    command: ["/docker-entrypoint.sh"]
    volumes:
      - /log/meraki_monitor:/srv/logs
    ports:
      - "8001:80"
    depends_on:
      - db
