version: '3'

services:
  db:
    image: postgres:10.3-alpine
    volumes:
      - /data/wellmans:/var/lib/postgresql/data
  web:
    image: cait/wellmans_django
    command: ["/docker-entrypoint.sh"]
    ports:
      - "8000:80"
    depends_on:
      - db
